version: 2

attach_workspace: &attach_workspace
    attach_workspace:
        at: ~/project

jobs:
  test_node_6:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: npm test

  test_node_8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm test

  release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run semantic-release

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test_node_6
      - test_node_8
      - release:
          requires:
            - test_node_6
            - test_node_8
